name: eopf-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - bottleneck=1.3.2
  - dask=2021.11.2
  - netcdf4=1.5.7
  - numpy=1.20.3
  - python=3.9.7
  - xarray=0.20.1
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - hypothesis=6.29.0
  - flake8=4.0.1
  - black=21.11b1
  - jupyter_sphinx=0.3.2
  - pre-commit=2.16.0
  - bandit=1.7.1
  - fsspec=2021.11.1
  - zarr=2.10.3
  - pyfakefs=4.5.4
  - mypy=0.931
  - pip
  - pip:
    - pyre-check==0.9.8
    - yummy-sphinx-theme==0.1.1
    - jinja2==2.11.3
    - ipython==7.30.0
    - isort==5.10.1
