[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eopf"
authors = []
dynamic = ["version", "description"]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Private :: Do Not Upload",
]
requires-python = ">=3.7"
dependencies = [
    "dask ==2021.11.2",
    "xarray ==0.20.1",
    "netcdf4 ==1.5.7",
    "numpy ==1.20.3",
    "bottleneck ==1.3.2",
]
license = {file = "LICENSE"}

[project.optional-dependencies]
test = [
    "pytest ==6.2.5",
    "pytest-cov ==3.0.0",
    "hypothesis ==6.29.0",
]
doc = ["jupyter_sphinx"]
