@startuml
left to right direction
package eopf.product.storage
{

    ' inspired by fsspec.spec.AbstractFileSystem
    abstract EOProductStore {
        __ Abrastract Methods __
        __init__(self[, url, mode, encoding, **kwargs]): Constructor
        __enter__(self): open the store on "with" statement
        __exit__(self, exc_type, exc_value, traceback): close the store on "with" statement
        open(self): open the store
        close(self): close the store
        listdir(self[, path]): list the given path or root
        rmdir(self, ): rm the given path or self
        rename(self, src, dest): rename src by dest
        clear(self): clear all the store
        getsize(self[, path]): return the size of the given storage
        dir_path(self[, path]): return the current path
        save(self[, path]): save locally at the given path

        __ Field Member __
        map: fsspec.FSMap

        __ Property __
        is_readable
        is_writeable
        is_listable
        is_erasable
    }

    EOZarrStore --|> EOProductStore
    EOCoGStore --|> EOProductStore
    EOHDF5Store --|> EOProductStore
}


package collections.abc {
    abstract MutableMapping
    abstract Mapping
    MutableMapping --|> Mapping
}
note bottom: Python legacy module

EOProductStore --|> MutableMapping
EOProductStore "1"*--"1" fsspec.spec.FSMap
@enduml
