@startuml
left to right direction
package "eopf.product" {

    class EOGroup {
        __ Methods __
        __init__(self, name, product[, relative_path, dataset]): Constructor
        __getattr__(self, key): access to the given key as a member field
        __str__(self) -> str: string readable representation
        __repr__(self) -> str: unique identifying string
        _repr_html_(self) -> html representation for jupyter notebook
        _ipython_key_completions_(self) -> Iterable[str]: keys for completion by ipython
        sel(): can be used only by final groups -> xarray.dataset
        isel(): can be used only by final groups -> xarray.dataset
        to_product(): convert this group to a product
        add_group(self, name): create a subgroup
        add_variable(self, name, data, **kwargs): create an eovariable
        write(self): write this group using the store
        _get_item(self, name): get the eogroup or eovaribale from the given key in memory and/or the store

        __ Property __
        name: str
        coordianates: EOGroup
        dims: tuple
        groups: key value pair for subgroup
        variables: key value pair for variables


        __ Field Members __
        _name: str
        _store: EOProductStore
        _dataset: xarray.Dataset
        _product: EOProduct
        _items: dict[str, EOGroup], memory storage of subgroups
        _relative_path: list[str], path from product level

    }

    class EOVariable

    package store
    {
        ' inspired by fsspec.spec.AbstractFileSystem
        abstract EOProductStore
    }

    EOGroup "1" o-- "0..*" EOVariable
    EOGroup "1" o-- "0..*" EOGroup
    EOGroup "1" o-- "0..*" EOAttributes

    EOGroup "1" *-- "1" EOProductStore


}

package collections.abc {
    abstract MutableMapping
    abstract Mapping
    MutableMapping --|> Mapping
}
note bottom: Python legacy module
EOGroup --|> MutableMapping
EOGroup "1" *-- "1" xarray.Dataset
note right: Pypi module

@enduml
