@startuml
' left to right direction
package "eopf.product" {
    ' this class will be used as set of functions
    ' that giving access to the EOProducts
    ' just a design class and all methods should be available
    ' at the parent module level.
    class EOTools
    {
        open(name,mode,...)
    }

    class EOProduct
    class EOGroup
    class EOVariableOperatorsMixin
    class EOVariable

    package store
    {
        ' inspired by fsspec.spec.AbstractFileSystem
        abstract EOProductStore
        EOZarrStore --|> EOProductStore
        EOCoGStore --|> EOProductStore
        EOHDF5Store --|> EOProductStore
    }
    EOProduct <-- EOTools : uses

    EOProduct "1" o-- "1..*" EOGroup
    EOGroup "1" o-- "0..*" EOVariable
    EOGroup "1" o-- "0..*" EOGroup
    EOGroup "1" o-- "0..*" EOAttributes
    EOVariableOperatorsMixin <|-- EOVariable

    EOProductStore <-- EOTools : uses
    EOProduct "1" *-- "1" EOProductStore
    EOGroup "1" *-- "1" EOProductStore
    EOvariable "1" *-- "1" EOProductStore

}

package xarray {
    class DataArray
}
note bottom: Pypi package

package collections.abc {
    abstract MutableMapping
    abstract Mapping
    MutableMapping --|> Mapping
}
note bottom: Python legacy module

EOProduct --|> MutableMapping
EOGroup --|> MutableMapping
EOVariable --|> MutableMapping
EOProductStore --|> MutableMapping

EOVariable "1" *-- "1" DataArray

@enduml
