@startuml
left to right direction
package eopf.product.storage
{

    ' inspired by fsspec.spec.AbstractFileSystem
    abstract EOProductStore {
        __ Abrastract Methods __
        __init__(self[, url, mode, encoding, **kwargs]): Constructor
        __enter__(self): open the store on "with" statement
        __exit__(self, exc_type, exc_value, traceback): close the store on "with" statement
        open(self, mode='r', **kwargs): open the store
        close(self): close the store
        listdir(self[, path]): list the given path or root
        rmdir(self, ): rm the given path or self
        clear(self): clear all the store
        getsize(self[, path]): return the size of the given storage
        dir_path(self[, path]): return the current path
        is_group(self, path): check if the given path is a group
        is_variable(self, path): check if the given path is a variable
        add_group(self, name[, relative_path]): add a group a the given path from the root
        add_variables(self, name, dataset[, relative_path]): add variables at the given path from the root
        iter(self, path): iter over the given path

        __ Field Member __
        url: str

        __ Property __
        is_readable: bool
        is_writeable: bool
        is_listable: bool
        is_erasable: bool
        map: fsspec.FSMap
        status: open or close

    }

    EOZarrStore --|> EOProductStore
    EOCoGStore --|> EOProductStore
    EOHDF5Store --|> EOProductStore
}


package collections.abc {
    abstract MutableMapping
    abstract Mapping
    MutableMapping --|> Mapping
}
note bottom: Python legacy module

EOProductStore --|> MutableMapping
EOProductStore "1"*--"1" fsspec.spec.FSMap
@enduml
