"""Provide generique Exceptions and Warnings for eopf modules"""
from .errors import (
    DaskProfilerError,
    EOObjectExistError,
    EOObjectMultipleParentError,
    EOPCConfigFactoryAlreadyDefaultConfiguration,
    EOPCConfigFactoryNoDefaultConfiguration,
    EOTriggeringConfigurationError,
    FormattingDecoratorMissingUri,
    FormattingError,
    InvalidProductError,
    LoggingConfigurationAlreadyExists,
    LoggingConfigurationDirDoesNotExist,
    LoggingConfigurationFileIsNotValid,
    LoggingConfigurationFileTypeNotSupported,
    LoggingConfigurationNotRegistered,
    MissingConfigurationParameter,
    SingleThreadProfilerError,
    StoreNotDefinedError,
    StoreNotOpenError,
    XmlManifestNetCDFError,
    XmlParsingError,
)

__all__ = [
    "EOObjectExistError",
    "EOObjectMultipleParentError",
    "InvalidProductError",
    "MissingConfigurationParameter",
    "StoreNotDefinedError",
    "StoreNotOpenError",
    "XmlParsingError",
    "LoggingConfigurationDirDoesNotExist",
    "LoggingConfigurationAlreadyExists",
    "LoggingConfigurationFileTypeNotSupported",
    "LoggingConfigurationNotRegistered",
    "LoggingConfigurationFileIsNotValid",
    "DaskProfilerError",
    "SingleThreadProfilerError",
    "FormattingError",
    "FormattingDecoratorMissingUri",
    "XmlManifestNetCDFError",
    "EOPCConfigFactoryNoDefaultConfiguration",
    "EOPCConfigFactoryAlreadyDefaultConfiguration",
    "EOTriggeringConfigurationError",
]
